pipeline {
    agent any
    stages {
        stage('Build') {
            agent {
                echo ' hello mon test'
            }
            steps {
                sh 'gradle --version'
            }
        }
    }
}
